services:
  - type: web
    name: headctrl-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend:app
    envVars:
      - key: MYSQL_ADDON_HOST
        sync: false
      - key: MYSQL_ADDON_PORT
        sync: false
      - key: MYSQL_ADDON_DB
        sync: false
      - key: MYSQL_ADDON_USER
        sync: false
      - key: MYSQL_ADDON_PASSWORD
        sync: false